//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPG.Domain.SharedKernel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPG.Domain.SharedKernel.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توسط کاربر لغو شده.
        /// </summary>
        internal static string CanceledByUser {
            get {
                return ResourceManager.GetString("CanceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاریزما کارت.
        /// </summary>
        internal static string CharismaCard {
            get {
                return ResourceManager.GetString("CharismaCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشت مستقیم.
        /// </summary>
        internal static string DirectDebit {
            get {
                return ResourceManager.GetString("DirectDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفق.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نویس.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منقضی شده.
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناموفق.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار دریافت اطلاعات تراکنش.
        /// </summary>
        internal static string FetchingResult {
            get {
                return ResourceManager.GetString("FetchingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال انجام.
        /// </summary>
        internal static string InPrgress {
            get {
                return ResourceManager.GetString("InPrgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر آدرس &apos;{0}&apos; در محدوده مجاز نمی باشد.
        /// </summary>
        internal static string InvalidUrlCharacterLimit {
            get {
                return ResourceManager.GetString("InvalidUrlCharacterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت آدرس &apos;{0}&apos; معتبر نمی باشد.
        /// </summary>
        internal static string InvalidUrlFormat {
            get {
                return ResourceManager.GetString("InvalidUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه پرداخت.
        /// </summary>
        internal static string IPG {
            get {
                return ResourceManager.GetString("IPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیش واریزی.
        /// </summary>
        internal static string PaymentReceipt {
            get {
                return ResourceManager.GetString("PaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتقل شده به سی پی جی.
        /// </summary>
        internal static string RedirectedToCpg {
            get {
                return ResourceManager.GetString("RedirectedToCpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درخواست تسویه ناموفق.
        /// </summary>
        internal static string SettlementFailed {
            get {
                return ResourceManager.GetString("SettlementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درخواست تسویه موفق.
        /// </summary>
        internal static string SettlementSucceeded {
            get {
                return ResourceManager.GetString("SettlementSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفق و در انتظار تایید.
        /// </summary>
        internal static string SucceededAndWaitingForVerification {
            get {
                return ResourceManager.GetString("SucceededAndWaitingForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش توسط برنامه لغو شد.
        /// </summary>
        internal static string TransactionCanceledByApplication {
            get {
                return ResourceManager.GetString("TransactionCanceledByApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو تراکنش ناموفق شد.
        /// </summary>
        internal static string TransactionCancellationFailed {
            get {
                return ResourceManager.GetString("TransactionCancellationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش با موفقیت لغو شد.
        /// </summary>
        internal static string TransactionCancellationSucceeded {
            get {
                return ResourceManager.GetString("TransactionCancellationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش ناموفق.
        /// </summary>
        internal static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش موفق.
        /// </summary>
        internal static string TransactionSucceeded {
            get {
                return ResourceManager.GetString("TransactionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش توسط برنامه تایید شد.
        /// </summary>
        internal static string TransactionVerifiedByApplication {
            get {
                return ResourceManager.GetString("TransactionVerifiedByApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش در انتظار تایید .
        /// </summary>
        internal static string TransactionWaitingForVerification {
            get {
                return ResourceManager.GetString("TransactionWaitingForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید ناموفق در درگاه.
        /// </summary>
        internal static string VerificationFailed {
            get {
                return ResourceManager.GetString("VerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید موفق در درگاه.
        /// </summary>
        internal static string VerificationSucceeded {
            get {
                return ResourceManager.GetString("VerificationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار تایید تراکنش در درگاه.
        /// </summary>
        internal static string Verifying {
            get {
                return ResourceManager.GetString("Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار پاسخ از درگاه.
        /// </summary>
        internal static string WaitingForPspResponse {
            get {
                return ResourceManager.GetString("WaitingForPspResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار پاسخ از سرویس دهنده.
        /// </summary>
        internal static string WaitingForResponseFromProvider {
            get {
                return ResourceManager.GetString("WaitingForResponseFromProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار ثبت درخواست تسویه در درگاه.
        /// </summary>
        internal static string WaitingForSettlementRequest {
            get {
                return ResourceManager.GetString("WaitingForSettlementRequest", resourceCulture);
            }
        }
    }
}
