//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPG.Domain.AggregateModels.BankAggregate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPG.Domain.AggregateModels.BankAggregate.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک با شناسه {0} فعال می باشد.
        /// </summary>
        internal static string BankIsAlreadyActive {
            get {
                return ResourceManager.GetString("BankIsAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک با شناسه {0} غیرفعال می باشد.
        /// </summary>
        internal static string BankIsAlreadyNotActive {
            get {
                return ResourceManager.GetString("BankIsAlreadyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه شبا {0} نامعتبر می باشد.
        /// </summary>
        internal static string InvalidIbanPrefix {
            get {
                return ResourceManager.GetString("InvalidIbanPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نوع سرویس دهنده {0} نامعتبر می باشد.
        /// </summary>
        internal static string InvalidProviderType
        {
            get
            {
                return ResourceManager.GetString("InvalidProviderType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سقف مجاز برداشت روزانه نامعتبر است.
        /// </summary>
        internal static string InvalidMaxWithdrawalAmountPerDay
        {
            get
            {
                return ResourceManager.GetString("InvalidMaxWithdrawalAmountPerDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شناسه بانک برای برداشت مستقیم در سرویس دهنده مورد نظر نامعتبر است
        /// </summary>
        internal static string InvalidDDBankCode
        {
            get
            {
                return ResourceManager.GetString("InvalidDDBankCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to وارد نمودن اطلاعات برداشت مستقیم الزامی می باشد
        /// </summary>
        internal static string RequiredDirectDebitSetting
        {
            get
            {
                return ResourceManager.GetString("RequiredDirectDebitSetting", resourceCulture);
            }
        }
        
    }
}
