//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPG.Application.Shared.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPG.Application.Shared.Resource.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNumber.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active/DeActive.
        /// </summary>
        public static string Active_DeActive {
            get {
                return ResourceManager.GetString("Active/DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationLogo.
        /// </summary>
        public static string ApplicationLogo {
            get {
                return ResourceManager.GetString("ApplicationLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application with Id {0} has not been found..
        /// </summary>
        public static string ApplicationNotFound {
            get {
                return ResourceManager.GetString("ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationSettings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsanPardakht.
        /// </summary>
        public static string AsanPardakht {
            get {
                return ResourceManager.GetString("AsanPardakht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankName.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank with Id {0} has not been found..
        /// </summary>
        public static string BankNotFound {
            get {
                return ResourceManager.GetString("BankNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        public static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseOnMinute.
        /// </summary>
        public static string BaseOnMinute {
            get {
                return ResourceManager.GetString("BaseOnMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrokerageCharisma.
        /// </summary>
        public static string BrokerageCharisma {
            get {
                return ResourceManager.GetString("BrokerageCharisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallbackUrls.
        /// </summary>
        public static string CallbackUrls {
            get {
                return ResourceManager.GetString("CallbackUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseMethodPayment.
        /// </summary>
        public static string ChooseMethodPayment {
            get {
                return ResourceManager.GetString("ChooseMethodPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyDepositByCompanyIdNotFound.
        /// </summary>
        public static string CompanyDepositByCompanyIdNotFound {
            get {
                return ResourceManager.GetString("CompanyDepositByCompanyIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companyDepositNotFound.
        /// </summary>
        public static string CompanyDepositNotFound {
            get {
                return ResourceManager.GetString("CompanyDepositNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyIPGDeposits.
        /// </summary>
        public static string CompanyIPGDeposits {
            get {
                return ResourceManager.GetString("CompanyIPGDeposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyIPGNotFound.
        /// </summary>
        public static string CompanyIPGNotFound {
            get {
                return ResourceManager.GetString("CompanyIPGNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, company &quot;{0}&quot; is inactive right now and unable for payment. Call support team or try later.
        /// </summary>
        public static string CompanyIsInactive {
            get {
                return ResourceManager.GetString("CompanyIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyLogo.
        /// </summary>
        public static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyNotFound.
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanySettings.
        /// </summary>
        public static string CompanySettings {
            get {
                return ResourceManager.GetString("CompanySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPGReferencePage.
        /// </summary>
        public static string CPGReferencePage {
            get {
                return ResourceManager.GetString("CPGReferencePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateApplication.
        /// </summary>
        public static string CreateApplication {
            get {
                return ResourceManager.GetString("CreateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateCompany.
        /// </summary>
        public static string CreateCompany {
            get {
                return ResourceManager.GetString("CreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDeposit.
        /// </summary>
        public static string CreateDeposit {
            get {
                return ResourceManager.GetString("CreateDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDepositCompanyFor.
        /// </summary>
        public static string CreateDepositCompanyFor {
            get {
                return ResourceManager.GetString("CreateDepositCompanyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateIPG.
        /// </summary>
        public static string CreateIPG {
            get {
                return ResourceManager.GetString("CreateIPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateIPGCompanyFor.
        /// </summary>
        public static string CreateIPGCompanyFor {
            get {
                return ResourceManager.GetString("CreateIPGCompanyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateProvider.
        /// </summary>
        public static string CreateProvider {
            get {
                return ResourceManager.GetString("CreateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeActive.
        /// </summary>
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultDeposit.
        /// </summary>
        public static string DefaultDeposit {
            get {
                return ResourceManager.GetString("DefaultDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultIPGDeposit.
        /// </summary>
        public static string DefaultIPGDeposit {
            get {
                return ResourceManager.GetString("DefaultIPGDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepositAmount.
        /// </summary>
        public static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits.
        /// </summary>
        public static string Deposits {
            get {
                return ResourceManager.GetString("Deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDebit.
        /// </summary>
        public static string DirectDebit {
            get {
                return ResourceManager.GetString("DirectDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EnglishName &apos;{0}&apos; has already been created.
        /// </summary>
        public static string DuplicateEnglishName {
            get {
                return ResourceManager.GetString("DuplicateEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateIban.
        /// </summary>
        public static string DuplicateIban {
            get {
                return ResourceManager.GetString("DuplicateIban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PersianName &apos;{0}&apos; has already been created.
        /// </summary>
        public static string DuplicatePersianName {
            get {
                return ResourceManager.GetString("DuplicatePersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishName.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInConnection.
        /// </summary>
        public static string ErrorInConnection {
            get {
                return ResourceManager.GetString("ErrorInConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForCompany.
        /// </summary>
        public static string ForCompany {
            get {
                return ResourceManager.GetString("ForCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iban.
        /// </summary>
        public static string Iban {
            get {
                return ResourceManager.GetString("Iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IbanPrefix.
        /// </summary>
        public static string IbanPrefix {
            get {
                return ResourceManager.GetString("IbanPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdpClientIds.
        /// </summary>
        public static string IdpClientIds {
            get {
                return ResourceManager.GetString("IdpClientIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:{0}.
        /// </summary>
        public static string IdpUserProfileException {
            get {
                return ResourceManager.GetString("IdpUserProfileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternetPaymentGateway.
        /// </summary>
        public static string InternetPaymentGateway {
            get {
                return ResourceManager.GetString("InternetPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PaymentRequest found having this Code or TrackId.
        /// </summary>
        public static string InvalidCodeOrTrackIdException {
            get {
                return ResourceManager.GetString("InvalidCodeOrTrackIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpgRedirectionMethodType.
        /// </summary>
        public static string IpgRedirectionMethodType {
            get {
                return ResourceManager.GetString("IpgRedirectionMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPGs.
        /// </summary>
        public static string IPGs {
            get {
                return ResourceManager.GetString("IPGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPGTypeId.
        /// </summary>
        public static string IPGTypeId {
            get {
                return ResourceManager.GetString("IPGTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPGType with Id {0} has not been found.
        /// </summary>
        public static string IPGTypeNotFound {
            get {
                return ResourceManager.GetString("IPGTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodTypes.
        /// </summary>
        public static string MethodTypes {
            get {
                return ResourceManager.GetString("MethodTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinioException.
        /// </summary>
        public static string MinioException {
            get {
                return ResourceManager.GetString("MinioException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalCodeMatchingRequied.
        /// </summary>
        public static string NationalCodeMatchingRequied {
            get {
                return ResourceManager.GetString("NationalCodeMatchingRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalCodeMatchingRequiedWithCardNumber.
        /// </summary>
        public static string NationalCodeMatchingRequiedWithCardNumber {
            get {
                return ResourceManager.GetString("NationalCodeMatchingRequiedWithCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackId not found.
        /// </summary>
        public static string NotFoundTrackIdException {
            get {
                return ResourceManager.GetString("NotFoundTrackIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParseCompanyIpgProviderData.
        /// </summary>
        public static string ParseCompanyIpgProviderData {
            get {
                return ResourceManager.GetString("ParseCompanyIpgProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay : &quot;{0} rial&quot; | {1} tooman for company : {2}.
        /// </summary>
        public static string PaymentMessage {
            get {
                return ResourceManager.GetString("PaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentReceipt.
        /// </summary>
        public static string PaymentReceipt {
            get {
                return ResourceManager.GetString("PaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, the payment address has expired, repeat the operation if necessary.
        /// </summary>
        public static string PaymentRequestCodeIsExpired {
            get {
                return ResourceManager.GetString("PaymentRequestCodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, this request has already been finalized.
        /// </summary>
        public static string PaymentRequestCodeIsFinalized {
            get {
                return ResourceManager.GetString("PaymentRequestCodeIsFinalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, this address has already been used, repeat the operation if necessary.
        /// </summary>
        public static string PaymentRequestCodeIsUsed {
            get {
                return ResourceManager.GetString("PaymentRequestCodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, the payment address is invalid.
        /// </summary>
        public static string PaymentRequestCodeNotFound {
            get {
                return ResourceManager.GetString("PaymentRequestCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentRequestDuplicateTrackerId.
        /// </summary>
        public static string PaymentRequestDuplicateTrackerId {
            get {
                return ResourceManager.GetString("PaymentRequestDuplicateTrackerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IbanCompanyInActive.
        /// </summary>
        public static string PaymentRequestIbanCompanyInActive {
            get {
                return ResourceManager.GetString("PaymentRequestIbanCompanyInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotDefinedCompanyDeposit.
        /// </summary>
        public static string PaymentRequestNotDefinedCompanyDeposit {
            get {
                return ResourceManager.GetString("PaymentRequestNotDefinedCompanyDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentRequestNotFound.
        /// </summary>
        public static string PaymentRequestNotFound {
            get {
                return ResourceManager.GetString("PaymentRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotMatchIbanAndCompany.
        /// </summary>
        public static string PaymentRequestNotMatchIbanAndCompany {
            get {
                return ResourceManager.GetString("PaymentRequestNotMatchIbanAndCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentRequestRequiredIbanOrCompany.
        /// </summary>
        public static string PaymentRequestRequiredIbanOrCompany {
            get {
                return ResourceManager.GetString("PaymentRequestRequiredIbanOrCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, the request status is invalid.
        /// </summary>
        public static string PaymentRequestStatusIsInvalid {
            get {
                return ResourceManager.GetString("PaymentRequestStatusIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersianName.
        /// </summary>
        public static string PersianName {
            get {
                return ResourceManager.GetString("PersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProviderId.
        /// </summary>
        public static string ProviderId {
            get {
                return ResourceManager.GetString("ProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProviderLogo.
        /// </summary>
        public static string ProviderLogo {
            get {
                return ResourceManager.GetString("ProviderLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider with Id {0} has not been found..
        /// </summary>
        public static string ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProviderType.
        /// </summary>
        public static string ProviderType {
            get {
                return ResourceManager.GetString("ProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RayanReferencePage.
        /// </summary>
        public static string RayanReferencePage {
            get {
                return ResourceManager.GetString("RayanReferencePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code or TrackId is required.
        /// </summary>
        public static string RequiredCodeOrTrackIdException {
            get {
                return ResourceManager.GetString("RequiredCodeOrTrackIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResponseApiUrl.
        /// </summary>
        public static string ResponseApiUrl {
            get {
                return ResourceManager.GetString("ResponseApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rial.
        /// </summary>
        public static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetActive.
        /// </summary>
        public static string SetActive {
            get {
                return ResourceManager.GetString("SetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetDeActive.
        /// </summary>
        public static string SetDeActive {
            get {
                return ResourceManager.GetString("SetDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteAddressCompany.
        /// </summary>
        public static string SiteAddressCompany {
            get {
                return ResourceManager.GetString("SiteAddressCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TitleMainMenu.
        /// </summary>
        public static string TitleMainMenu {
            get {
                return ResourceManager.GetString("TitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooman.
        /// </summary>
        public static string Tooman {
            get {
                return ResourceManager.GetString("Tooman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackId status is invalid.
        /// </summary>
        public static string TrackIdInvalidStatusException {
            get {
                return ResourceManager.GetString("TrackIdInvalidStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionNotFound.
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again or contact support.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsersNotFound.
        /// </summary>
        public static string UsersNotFound {
            get {
                return ResourceManager.GetString("UsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBan Validation.
        /// </summary>
        public static string Validation_IBan {
            get {
                return ResourceManager.GetString("Validation_IBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation is required.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vandar.
        /// </summary>
        public static string Vandar {
            get {
                return ResourceManager.GetString("Vandar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerificationTimeLimit.
        /// </summary>
        public static string VerificationTimeLimit {
            get {
                return ResourceManager.GetString("VerificationTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerificationTimeLimitIPG.
        /// </summary>
        public static string VerificationTimeLimitIPG {
            get {
                return ResourceManager.GetString("VerificationTimeLimitIPG", resourceCulture);
            }
        }
    }
}
