//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPG.Application.Shared.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPG.Application.Shared.Resource.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active/DeActive.
        /// </summary>
        public static string Active_DeActive {
            get {
                return ResourceManager.GetString("Active/DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationLogo.
        /// </summary>
        public static string ApplicationLogo {
            get {
                return ResourceManager.GetString("ApplicationLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application with Id {0} has not been found..
        ///   Looks up a localized string similar to Application with Id {0} has not been found..
        /// </summary>
        public static string ApplicationNotFound {
            get {
                return ResourceManager.GetString("ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationSettings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank with Id {0} has not been found..
        /// </summary>
        public static string BankNotFound {
            get {
                return ResourceManager.GetString("BankNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        public static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrokerageCharisma.
        /// </summary>
        public static string BrokerageCharisma {
            get {
                return ResourceManager.GetString("BrokerageCharisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companyDepositNotFound.
        /// </summary>
        public static string CompanyDepositNotFound {
            get {
                return ResourceManager.GetString("CompanyDepositNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyLogo.
        /// </summary>
        public static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyIPGNotFound.
        /// </summary>
        public static string CompanyIPGNotFound {
            get {
                return ResourceManager.GetString("CompanyIPGNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyNotFound.
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateApplication.
        /// </summary>
        public static string CreateApplication {
            get {
                return ResourceManager.GetString("CreateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateCompany.
        /// </summary>
        public static string CreateCompany {
            get {
                return ResourceManager.GetString("CreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeActive.
        /// </summary>
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDebit.
        /// </summary>
        public static string DirectDebit {
            get {
                return ResourceManager.GetString("DirectDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EnglishName &apos;{0}&apos; has already been created.
        /// </summary>
        public static string DuplicateEnglishName {
            get {
                return ResourceManager.GetString("DuplicateEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateIban.
        /// </summary>
        public static string DuplicateIban {
            get {
                return ResourceManager.GetString("DuplicateIban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PersianName &apos;{0}&apos; has already been created.
        /// </summary>
        public static string DuplicatePersianName {
            get {
                return ResourceManager.GetString("DuplicatePersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishName.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IbanPrefix.
        /// </summary>
        public static string IbanPrefix {
            get {
                return ResourceManager.GetString("IbanPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdpClientIds.
        /// </summary>
        public static string IdpClientIds {
            get {
                return ResourceManager.GetString("IdpClientIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternetPaymentGateway.
        /// </summary>
        public static string InternetPaymentGateway {
            get {
                return ResourceManager.GetString("InternetPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPGType with Id {0} has not been found.
        /// </summary>
        public static string IPGTypeNotFound {
            get {
                return ResourceManager.GetString("IPGTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodTypes.
        /// </summary>
        public static string MethodTypes {
            get {
                return ResourceManager.GetString("MethodTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalCodeMatchingRequied.
        /// </summary>
        public static string NationalCodeMatchingRequied {
            get {
                return ResourceManager.GetString("NationalCodeMatchingRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalCodeMatchingRequiedWithCardNumber.
        /// </summary>
        public static string NationalCodeMatchingRequiedWithCardNumber {
            get {
                return ResourceManager.GetString("NationalCodeMatchingRequiedWithCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentReceipt.
        /// </summary>
        public static string PaymentReceipt {
            get {
                return ResourceManager.GetString("PaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersianName.
        /// </summary>
        public static string PersianName {
            get {
                return ResourceManager.GetString("PersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider with Id {0} has not been found..
        /// </summary>
        public static string ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResponseApiUrl.
        /// </summary>
        public static string ResponseApiUrl {
            get {
                return ResourceManager.GetString("ResponseApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetActive.
        /// </summary>
        public static string SetActive {
            get {
                return ResourceManager.GetString("SetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetDeActive.
        /// </summary>
        public static string SetDeActive {
            get {
                return ResourceManager.GetString("SetDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TitleMainMenu.
        /// </summary>
        public static string TitleMainMenu {
            get {
                return ResourceManager.GetString("TitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsersNotFound.
        /// </summary>
        public static string UsersNotFound {
            get {
                return ResourceManager.GetString("UsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation_Required.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
