<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Daryaftyar.Application\Daryaftyar.Application.csproj" />
    <ProjectReference Include="..\Daryaftyar.Domain\Daryaftyar.Domain.csproj" />
  </ItemGroup>

</Project>
