//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPG.Domain.AggregateModels.ApplicationAggregate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPG.Domain.AggregateModels.ApplicationAggregate.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه با شناسه {0} فعال می باشد.
        /// </summary>
        internal static string ApplicationIsAlreadyActive {
            get {
                return ResourceManager.GetString("ApplicationIsAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه با شناسه {0} غیرفعال می باشد.
        /// </summary>
        internal static string ApplicationIsAlreadyNotActive {
            get {
                return ResourceManager.GetString("ApplicationIsAlreadyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه موجود نمی باشد.
        /// </summary>
        internal static string ApplicationNotFound {
            get {
                return ResourceManager.GetString("ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی بازگشتی تکراری است.
        /// </summary>
        internal static string Duplicate_CallbackUrl {
            get {
                return ResourceManager.GetString("Duplicate_CallbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه Idp تکراری است.
        /// </summary>
        internal static string Duplicate_IdpClientId {
            get {
                return ResourceManager.GetString("Duplicate_IdpClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه یا شناسه های {0} قبلا ثبت شده است.
        /// </summary>
        internal static string Duplicate_IdpClientIds {
            get {
                return ResourceManager.GetString("Duplicate_IdpClientIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه idp غیرفعال می باشد.
        /// </summary>
        internal static string IdpClientIdIsNotActive {
            get {
                return ResourceManager.GetString("IdpClientIdIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی بازگشتی موجود نمی باشد.
        /// </summary>
        internal static string Invalid_CallbackUrl {
            get {
                return ResourceManager.GetString("Invalid_CallbackUrl", resourceCulture);
            }
        }
    }
}
