//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPG.Domain.AggregateModels.CompanyAggregate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPG.Domain.AggregateModels.CompanyAggregate.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ایجاد رکورد جدید.
        /// </summary>
        internal static string cannot_create_company {
            get {
                return ResourceManager.GetString("cannot_create_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت مورد نظر هیچ حسابی ندارد.
        /// </summary>
        internal static string CompanyHasNotCompanyDeposit {
            get {
                return ResourceManager.GetString("CompanyHasNotCompanyDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت فعال نمی باشد.
        /// </summary>
        internal static string CompanyIsAlreadyNotActive {
            get {
                return ResourceManager.GetString("CompanyIsAlreadyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام انگلیسی تکراری است.
        /// </summary>
        internal static string Duplicate_EnglishName {
            get {
                return ResourceManager.GetString("Duplicate_EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش پرداخت تکراری است.
        /// </summary>
        internal static string Duplicate_PaymentMethodType {
            get {
                return ResourceManager.GetString("Duplicate_PaymentMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی تکراری است.
        /// </summary>
        internal static string Duplicate_PersianName {
            get {
                return ResourceManager.GetString("Duplicate_PersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام انگلیسی را وارد کنید.
        /// </summary>
        internal static string Empty_EnglishName {
            get {
                return ResourceManager.GetString("Empty_EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگو را وارد کنید.
        /// </summary>
        internal static string Empty_Logo {
            get {
                return ResourceManager.GetString("Empty_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش پرداخت را  وارد کنید.
        /// </summary>
        internal static string Empty_PaymentMethodType {
            get {
                return ResourceManager.GetString("Empty_PaymentMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی را وارد کنید.
        /// </summary>
        internal static string Empty_PersianName {
            get {
                return ResourceManager.GetString("Empty_PersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام انگلیسی مجاز نمی باشد.
        /// </summary>
        internal static string Invalid_EnglishName {
            get {
                return ResourceManager.GetString("Invalid_EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر نام  انگلیسی مجاز نمی باشد.
        /// </summary>
        internal static string Invalid_EnglishNameCharachterLimit {
            get {
                return ResourceManager.GetString("Invalid_EnglishNameCharachterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگو مجاز نمی باشد.
        /// </summary>
        internal static string Invalid_logo {
            get {
                return ResourceManager.GetString("Invalid_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند فایل مجاز نمی باشد.
        /// </summary>
        internal static string invalid_logo_extention {
            get {
                return ResourceManager.GetString("invalid_logo_extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت لوگو مجاز نمی باشد.
        /// </summary>
        internal static string Invalid_Logo_Format {
            get {
                return ResourceManager.GetString("Invalid_Logo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر لوگو مجاز نمی باشد.
        /// </summary>
        internal static string Invalid_Logo_path {
            get {
                return ResourceManager.GetString("Invalid_Logo_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش پرداخت نادرست است.
        /// </summary>
        internal static string Invalid_PaymentMethodType {
            get {
                return ResourceManager.GetString("Invalid_PaymentMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی مجاز نمی باشد.
        /// </summary>
        internal static string Invalid_PersianName {
            get {
                return ResourceManager.GetString("Invalid_PersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر نام  فارسی مجاز نمی باشد.
        /// </summary>
        internal static string Invalid_PersianNameCharachterLimit {
            get {
                return ResourceManager.GetString("Invalid_PersianNameCharachterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز لوگو مجاز نمی باشد.
        /// </summary>
        internal static string MaximalFileSize {
            get {
                return ResourceManager.GetString("MaximalFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
