<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="RabbitMQ\Envelope\Envelope.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Minio" Version="5.0.0" />
		<PackageReference Include="Minio.AspNetCore" Version="5.0.0" />
		<PackageReference Include="Charisma.MessagingContracts" Version="1.0.0.6184" />
		<PackageReference Include="Confluent.Kafka" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RabbitMQ.Client" Version="6.6.0" />
		<PackageReference Include="MassTransit" Version="8.0.1" />
		<PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CPG.Application\CPG.Application.csproj" />
		<ProjectReference Include="..\CPG.Domain\CPG.Domain.csproj" />
		<ProjectReference Include="..\CPG.Infrastructure.Authorization\CPG.Infrastructure.Authorization.csproj" />
		<ProjectReference Include="..\CPG.Infrastructure.Persistence\CPG.Infrastructure.Persistence.csproj" />
	</ItemGroup>

</Project>
