using CPG.Domain.SharedKernel;
using CPG.Domain.SharedKernel.Logging;
using FluentAssertions;
using System;
using System.Collections.Generic;
using Xunit;
using static CPG.Domain.SharedKernel.Enums;

namespace CPG.Domain.Tests.Unit.Infrastructure.Logging;

/// <summary>
/// Validation tests to ensure all 25 audit log parameters are correctly captured
/// for different scenarios: Client API calls, Provider calls, and User actions
/// </summary>
public class AuditLogValidationTests
{
    /// <summary>
    /// Test Case 1: Client API Call - Payment Request
    /// Validates all 25 parameters for a client-initiated payment request
    /// </summary>
    [Fact]
    public void Validate_All_25_Parameters_For_Client_Payment_Request()
    {
        // Arrange - Simulate a complete client payment request log
        var log = new RequestResponseLogModel
        {
            // 1. log_id - Generated by Elasticsearch (not in model, auto-generated)
            // 2. timestamp - Captured as RequestTime
            RequestTime = DateTime.UtcNow,

            // 3. audit_level - Implicitly "info" for successful requests
            // 4. audit_type - Client request
            AuditType = AuditType.Client,

            // 5. correlation_id - Tracks request across services (stored separately in HttpContext)
            // 6. request_id - Unique identifier for this specific request

            // 7. service_name
            ServiceName = "PaymentRequest",

            // 8. user_id
            UserId = 123,

            // 9. company_id
            CompanyId = 456,

            // 10. application_id
            ApplicationId = 789,

            // 11. client_id
            ClientId = "CLIENT-ABC-123",

            // 12. user_agent
            UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",

            // 13. client_ip
            IP = "192.168.1.100",

            // 14. http_method
            RequestMethod = "POST",

            // 15. endpoint_url
            Host = "api.cpg.com",

            // 16. query_params
            RequestQueryString = "?callback=https://merchant.com/callback",

            // 17. request_body
            RequestBody = new
            {
                amount = 1000000,
                orderId = "ORD-123",
                description = "Payment for order"
            },

            // 18. response_status
            ResponseStatus = "200",

            // 19. response_body
            ResponseBody = new
            {
                token = "TOKEN-ABC-123",
                redirectUrl = "https://gateway.com/pay"
            },

            // 20. start_time
            StartDateTime = DateTime.UtcNow,

            // 21. end_time
            EndDateTime = DateTime.UtcNow.AddSeconds(2),

            // 22. duration_ms
            DurationMs = 2000,

            // 23. is_success
            IsSuccess = true,

            // 24. error_code - null for successful requests
            ErrorCode = null,

            // 25. stack_trace - null for successful requests
            StackTrace = null
        };

        // Act & Assert - Verify all required fields are populated
        ValidateAllParameters(log, AuditType.Client, expectSuccess: true);
    }

    /// <summary>
    /// Test Case 2: Provider API Call - AsanPardakht Token Request
    /// Validates all 25 parameters for an external provider call
    /// </summary>
    [Fact]
    public void Validate_All_25_Parameters_For_Provider_Token_Request()
    {
        // Arrange - Simulate a provider call log
        var callLog = new CallLogModel
        {
            // 1-6. Metadata fields (handled by logging infrastructure)

            // 7. service_name (represented as ServiceCallUrl for providers)
            ServiceCallUrl = "https://api.asanpardakht.com/v1/token",

            // 8-11. User context
            CreationUserId = 123,
            // CompanyId and ApplicationId not directly in CallLogModel but tracked via HttpContext

            // 12-13. Client info (tracked via HttpContext)

            // 14-16. HTTP details
            // HTTP method embedded in service type

            // 17. request_body
            RequestBody = "{\"merchantId\":\"MERCHANT-123\",\"amount\":1000000}",

            // 18. response_status (derived from ServiceCallStatus)
            ServiceCallStatus = true,

            // 19. response_body
            ResponseBody = "{\"token\":\"PROVIDER-TOKEN-XYZ\",\"status\":\"success\"}",

            // 20-21. Timing
            ServiceCallDate = DateTime.UtcNow,
            CreationDate = DateTime.UtcNow.AddSeconds(1),

            // 22. duration_ms (calculated from ServiceCallDate and CreationDate)

            // 23. is_success
            // Represented by ServiceCallStatus = true

            // 24-25. Error details
            ErrorCode = null,
            ErrorType = null,

            // Additional provider-specific fields
            ServiceType = Enums.ServiceType.AsanPardakhtToken,
            ProviderType = ProviderTypeInLog.AsanPardakht,
            AuditType = AuditType.Provider,
            CorrolationId = "CORR-123-ABC"
        };

        // Act & Assert
        ValidateProviderCallParameters(callLog, expectSuccess: true);
    }

    /// <summary>
    /// Test Case 3: User Action - Login
    /// Validates all 25 parameters for a user-initiated action
    /// </summary>
    [Fact]
    public void Validate_All_25_Parameters_For_User_Login()
    {
        // Arrange
        var log = new RequestResponseLogModel
        {
            RequestTime = DateTime.UtcNow,
            AuditType = AuditType.User,
            ServiceName = "Login",

            // User context - null before authentication
            UserId = null,
            CompanyId = null,
            ApplicationId = null,
            ClientId = null,

            UserAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X)",
            IP = "10.0.0.50",
            RequestMethod = "POST",
            Host = "api.cpg.com",
            RequestQueryString = "",

            RequestBody = new
            {
                username = "user@example.com",
                password = "********" // Masked
            },

            ResponseStatus = "200",
            ResponseBody = new
            {
                token = "JWT-TOKEN-HERE",
                expiresIn = 3600
            },

            StartDateTime = DateTime.UtcNow,
            EndDateTime = DateTime.UtcNow.AddMilliseconds(500),
            DurationMs = 500,
            IsSuccess = true,
            ErrorCode = null,
            StackTrace = null
        };

        // Act & Assert
        ValidateAllParameters(log, AuditType.User, expectSuccess: true);
    }

    /// <summary>
    /// Test Case 4: Failed Provider Call with Timeout
    /// Validates error fields including stack_trace
    /// </summary>
    [Fact]
    public void Validate_All_25_Parameters_For_Provider_Timeout()
    {
        // Arrange
        var callLog = new CallLogModel
        {
            ServiceCallUrl = "https://api.behpardakht.com/verify",
            ServiceCallDate = DateTime.UtcNow,
            ServiceCallStatus = false,

            RequestBody = "{\"transactionId\":\"TXN-999\"}",
            ResponseBody = "TIMEOUT after 30500ms - The operation has timed out",

            ErrorCode = "RequestTimeout",
            ErrorType = "Timeout",

            ServiceType = Enums.ServiceType.BehPardakhtVerify,
            ProviderType = ProviderTypeInLog.BehPardakht,
            AuditType = AuditType.Provider,

            CreationUserId = 123,
            CreationDate = DateTime.UtcNow.AddSeconds(30),
            CorrolationId = "CORR-TIMEOUT-123"
        };

        // Act & Assert
        ValidateProviderCallParameters(callLog, expectSuccess: false);
        callLog.ErrorCode.Should().NotBeNullOrEmpty();
        callLog.ErrorType.Should().NotBeNullOrEmpty();
    }

    /// <summary>
    /// Test Case 5: Unhandled Exception with Stack Trace
    /// Validates stack_trace capture
    /// </summary>
    [Fact]
    public void Validate_All_25_Parameters_For_Unhandled_Exception()
    {
        // Arrange
        var log = new RequestResponseLogModel
        {
            RequestTime = DateTime.UtcNow,
            AuditType = AuditType.Develop,
            ServiceName = "PaymentRequest",

            UserId = 123,
            CompanyId = 456,
            ApplicationId = 789,

            UserAgent = "PostmanRuntime/7.29.0",
            IP = "192.168.1.100",
            RequestMethod = "POST",
            Host = "api.cpg.com",
            RequestQueryString = "",

            RequestBody = new { amount = -1000 }, // Invalid amount
            ResponseStatus = "500",
            ResponseBody = "Internal Server Error",

            StartDateTime = DateTime.UtcNow,
            EndDateTime = DateTime.UtcNow.AddMilliseconds(100),
            DurationMs = 100,

            IsSuccess = false,
            ErrorCode = "VALIDATION_ERROR",
            StackTrace = @"at CPG.Application.UseCases.PaymentRequests.CreatePaymentRequestCommandHandler.Handle()
   at CPG.API.Controllers.PaymentController.CreatePaymentRequest()"
        };

        // Act & Assert
        ValidateAllParameters(log, AuditType.Develop, expectSuccess: false);
        log.StackTrace.Should().NotBeNullOrEmpty();
        log.StackTrace.Should().Contain("CreatePaymentRequestCommandHandler");
    }

    /// <summary>
    /// Test Case 6: Client API Call with Authentication Context
    /// Validates mobile_phone and full user context
    /// </summary>
    [Fact]
    public void Validate_All_25_Parameters_With_Mobile_Phone()
    {
        // Arrange
        var log = new RequestResponseLogModel
        {
            RequestTime = DateTime.UtcNow,
            AuditType = AuditType.Client,
            ServiceName = "TransactionVerify",

            UserId = 999,
            CompanyId = 111,
            ApplicationId = 222,
            ClientId = "CLIENT-MOBILE-APP",
            MobilePhone = "09123456789", // Mobile phone for authentication tracking

            UserAgent = "MobileApp/1.5.0 (Android 12)",
            IP = "185.10.20.30",
            RequestMethod = "POST",
            Host = "api.cpg.com",
            RequestQueryString = "?transactionId=TXN-123",

            RequestBody = new { transactionId = "TXN-123" },
            ResponseStatus = "200",
            ResponseBody = new { status = "verified", amount = 50000 },

            StartDateTime = DateTime.UtcNow,
            EndDateTime = DateTime.UtcNow.AddSeconds(1),
            DurationMs = 1000,

            IsSuccess = true,
            ErrorCode = null,
            StackTrace = null
        };

        // Act & Assert
        ValidateAllParameters(log, AuditType.Client, expectSuccess: true);
        log.MobilePhone.Should().NotBeNullOrEmpty();
        log.MobilePhone.Should().MatchRegex(@"^09\d{9}$");
    }

    /// <summary>
    /// Validates all parameters are correctly populated for RequestResponseLogModel
    /// </summary>
    private void ValidateAllParameters(RequestResponseLogModel log, AuditType expectedAuditType, bool expectSuccess)
    {
        // 1. log_id - Auto-generated by Elasticsearch (not validated here)

        // 2. timestamp
        log.RequestTime.Should().NotBe(default(DateTime));
        log.RequestTime.Should().BeBefore(DateTime.UtcNow.AddMinutes(1));

        // 3. audit_level - Implicitly determined by log type (info/error/warn)

        // 4. audit_type
        log.AuditType.Should().Be(expectedAuditType);

        // 5-6. correlation_id and request_id - Tracked in HttpContext, not in model

        // 7. service_name
        log.ServiceName.Should().NotBeNullOrEmpty();

        // 8-11. User context (may be null for unauthenticated requests)
        if (expectedAuditType != AuditType.User || expectSuccess)
        {
            // For authenticated requests, at least one context field should be populated
        }

        // 12. user_agent
        log.UserAgent.Should().NotBeNull();

        // 13. client_ip
        log.IP.Should().NotBeNull();

        // 14. http_method
        log.RequestMethod.Should().NotBeNullOrEmpty();

        // 15. endpoint_url
        log.Host.Should().NotBeNullOrEmpty();

        // 16. query_params (can be empty)
        log.RequestQueryString.Should().NotBeNull();

        // 17. request_body
        log.RequestBody.Should().NotBeNull();

        // 18. response_status
        log.ResponseStatus.Should().NotBeNullOrEmpty();

        // 19. response_body
        log.ResponseBody.Should().NotBeNull();

        // 20. start_time
        log.StartDateTime.Should().NotBe(default(DateTime));

        // 21. end_time
        log.EndDateTime.Should().NotBe(default(DateTime));
        log.EndDateTime.Should().BeOnOrAfter(log.StartDateTime);

        // 22. duration_ms
        log.DurationMs.Should().BeGreaterThanOrEqualTo(0);

        // 23. is_success
        log.IsSuccess.Should().Be(expectSuccess);

        // 24-25. error_code and stack_trace
        if (expectSuccess)
        {
            log.ErrorCode.Should().BeNullOrEmpty();
            log.StackTrace.Should().BeNullOrEmpty();
        }
        else
        {
            log.ErrorCode.Should().NotBeNullOrEmpty();
            // stack_trace may or may not be present depending on error type
        }
    }

    /// <summary>
    /// Validates all parameters for CallLogModel (provider calls)
    /// </summary>
    private void ValidateProviderCallParameters(CallLogModel log, bool expectSuccess)
    {
        // Service information
        log.ServiceCallUrl.Should().NotBeNullOrEmpty();
        log.ServiceType.Should().NotBeNull();
        log.ProviderType.Should().NotBeNull();
        log.AuditType.Should().Be(AuditType.Provider);

        // Request/Response
        log.RequestBody.Should().NotBeNullOrEmpty();
        log.ResponseBody.Should().NotBeNullOrEmpty();

        // Status
        log.ServiceCallStatus.Should().Be(expectSuccess);

        // Timing
        log.ServiceCallDate.Should().NotBe(default(DateTime));
        log.CreationDate.Should().NotBe(default(DateTime));

        // User context
        log.CreationUserId.Should().BeGreaterThan(0);

        // Correlation
        log.CorrolationId.Should().NotBeNullOrEmpty();

        // Error details
        if (expectSuccess)
        {
            log.ErrorCode.Should().BeNullOrEmpty();
            log.ErrorType.Should().BeNullOrEmpty();
        }
        else
        {
            log.ErrorCode.Should().NotBeNullOrEmpty();
            log.ErrorType.Should().NotBeNullOrEmpty();
        }
    }

    /// <summary>
    /// Test to ensure all AuditType enum values are supported
    /// </summary>
    [Theory]
    [InlineData(AuditType.Client)]
    [InlineData(AuditType.Provider)]
    [InlineData(AuditType.User)]
    [InlineData(AuditType.Develop)]
    public void Validate_All_AuditType_Values_Are_Supported(AuditType auditType)
    {
        // Arrange & Act
        var log = new RequestResponseLogModel
        {
            AuditType = auditType,
            RequestTime = DateTime.UtcNow,
            ServiceName = "TestService",
            StartDateTime = DateTime.UtcNow,
            EndDateTime = DateTime.UtcNow,
            DurationMs = 0,
            IsSuccess = true
        };

        // Assert
        log.AuditType.Should().Be(auditType);
        Enum.IsDefined(typeof(AuditType), auditType).Should().BeTrue();
    }

    /// <summary>
    /// Test to ensure all ProviderTypeInLog enum values are supported
    /// </summary>
    [Theory]
    [InlineData(ProviderTypeInLog.AsanPardakht)]
    [InlineData(ProviderTypeInLog.Pec)]
    [InlineData(ProviderTypeInLog.BehPardakht)]
    [InlineData(ProviderTypeInLog.Sep)]
    [InlineData(ProviderTypeInLog.Vandar)]
    [InlineData(ProviderTypeInLog.NeoBank)]
    [InlineData(ProviderTypeInLog.CharisPay)]
    [InlineData(ProviderTypeInLog.CharismaCard)]
    [InlineData(ProviderTypeInLog.Idp)]
    public void Validate_All_ProviderType_Values_Are_Supported(ProviderTypeInLog providerType)
    {
        // Arrange & Act
        var log = new CallLogModel
        {
            ProviderType = providerType,
            AuditType = AuditType.Provider,
            ServiceCallDate = DateTime.UtcNow,
            CreationDate = DateTime.UtcNow,
            CreationUserId = 1
        };

        // Assert
        log.ProviderType.Should().Be(providerType);
        Enum.IsDefined(typeof(ProviderTypeInLog), providerType).Should().BeTrue();
    }
}
