<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AggregateModels\UserAggregate\Idp\**" />
    <EmbeddedResource Remove="AggregateModels\UserAggregate\Idp\**" />
    <None Remove="AggregateModels\UserAggregate\Idp\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" Version="4.2.0" />
    <PackageReference Include="Ardalis.Specification" Version="7.0.0" />
    <PackageReference Include="IdentityModel" Version="6.2.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="8.0.0" />
	  <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>CPG.Domain.Tests.Unit</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AggregateModels\ApplicationAggregate\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <Compile Update="AggregateModels\CompanyAggregate\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <Compile Update="AggregateModels\CompanyIPGAggregate\Resource.Designer.cs">
      <DependentUpon>Resource.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="AggregateModels\DirectDebitGrantAggregate\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <Compile Update="AggregateModels\PaymentRequestAggregate\Resource.Designer.cs">
      <DependentUpon>Resource.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="AggregateModels\ProviderAggregate\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <Compile Update="AggregateModels\CompanyDepositAggregate\Resource.Designer.cs">
      <DependentUpon>Resource.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="AggregateModels\UserAggregate\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <Compile Update="SharedKernel\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="AggregateModels\ApplicationAggregate\Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AggregateModels\CompanyAggregate\Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AggregateModels\CompanyIPGAggregate\Resource.resx">
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="AggregateModels\DirectDebitGrantAggregate\Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AggregateModels\PaymentRequestAggregate\Resource.resx">
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="AggregateModels\ProviderAggregate\Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AggregateModels\CompanyDepositAggregate\Resource.resx">
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="AggregateModels\UserAggregate\Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="SharedKernel\Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AggregateModels\ApplicationAggregate\Guards\" />
    <Folder Include="AggregateModels\CompanyAggregate\Guards\" />
    <Folder Include="AggregateModels\CompanyIPGAggregate\Events\" />
    <Folder Include="AggregateModels\CompanyIPGAggregate\Events\" />
    <Folder Include="AggregateModels\CompanyIPGAggregate\Guards\" />
    <Folder Include="AggregateModels\DirectDebitGrantAggregate\Exceptions\" />
    <Folder Include="AggregateModels\PaymentRequestAggregate\Events\" />
    <Folder Include="AggregateModels\ProviderAggregate\Guards\" />
    <Folder Include="AggregateModels\CompanyDepositAggregate\Guards\" />
    <Folder Include="SharedKernel\ApplicationSettings\Exceptions\" />
    <Folder Include="SharedKernel\ApplicationSettings\Commands\" />
  </ItemGroup>

</Project>
